name: RBO News Bot

on:
  schedule:
    - cron: "*/5 * * * *"  # every 5 minutes
  workflow_dispatch:       # manual run option

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          TELEGRAM_TOKEN: "8069359728:AAFTBVPn4vpX4pESSsb-91pcHrDckBlawdA"
          CHAT_ID: "Y844349255"
          FINNHUB_API_KEY: "d72s5fhr01qlfd9ocu2gd72s5fhr01qlfd9ocu30"
        run: python news_bot.py
